import { Asset } from "./../interfaceTS/interface";

export const Products: Asset[] = [
  {
    id: 1,
    name: "Sumsung s21 ultra ",
    price: 1000,
    description: "Sumsung s21 ultra is a special product",
    image:
      "https://megamir.by/image/cache/data/0000004/S21%20Ultra/samsung_galaxy_s21_ultra_88-1200x800.jpg",
    category: "phone",
    color: "SaddleBrown",
    comment: [],
    years: 2020,
    sale: 30,
    count: 1,
  },
  {
    id: 2,
    name: "Nike T-Shirt",
    price: 100,
    description: "Nike T-Shirt is a buatiful T-Shirt",
    image:
      "https://images.bike24.net/i/mb/e1/e2/4d/328978-00-d-689172-861094.jpg",
    category: "clothing",
    color: "MidnightBlue",
    comment: [],
    years: 2020,
    sale: 30,
    count: 1,
  },
  {
    id: 3,
    name: "Trousers addidas",
    price: 140,
    description: "Trousers addidas is a buatiful T-Shirt",
    image:
      "http://img03.taobaocdn.com/bao/uploaded/i3/12282018958518272/T1erIDXg8eXXXXXXXX_!!0-item_pic.jpg",
    category: "clothing",
    color: "black",
    comment: [],
    years: 2010,
    sale: 40,
    count: 1,
  },
  {
    id: 4,
    name: "In search of Alaska",
    price: 1300,
    description: "In search of Alaska is a buatiful book",
    image:
      "https://i.pinimg.com/originals/f4/de/9b/f4de9b05d03fdea166ac7f9ae9e8f0e2.jpg",
    category: "book",
    color: "black",
    comment: [],
    years: 2013,
    sale: 9,
    count: 1,
  },
  {
    id: 5,
    name: "sumsung s10",
    price: 1000,
    description: "sumsung s10 is a smart phone",
    image:
      "https://irichonline.ru/wp-content/uploads/2021/10/iphone-12-pro-graphite-hero.png",
    category: "phone",
    color: "black",
    comment: [],
    years: 2020,
    sale: 30,
    count: 1,
  },
  {
    id: 6,
    name: "sumsung s10",
    price: 1000,
    description: "sumsung s10 is a smart phone",
    image: "https://static.baza.farpost.ru/v/1607564614282_bulletin",
    category: "phone",
    color: "black",
    comment: [],
    years: 2020,
    sale: 30,
    count: 1,
  },
  {
    id: 7,
    name: "sumsung s10",
    price: 1000,
    description: "sumsung s10 is a smart phone",
    image:
      "https://zakaz64.ru/upload/iblock/2f3/bcopcdgfjfp3p9maf13za5e3c3tciq8f.png",
    category: "phone",
    color: "gray",
    comment: [],
    years: 2020,
    sale: 30,
    count: 1,
  },
  {
    id: 8,
    name: "Nike T-Shirt",
    price: 100,
    description: "Nike T-Shirt is a buatiful T-Shirt",
    image: "https://sport-style.by/3311-large_default/bryuki-063.jpg",
    category: "clothing",
    color: "gray",
    comment: [],
    years: 2020,
    sale: 30,
    count: 1,
  },
  {
    id: 9,
    name: "Nike T-Shirt",
    price: 100,
    description: "Nike T-Shirt is a buatiful T-Shirt",
    image: "https://cdn.yoox.biz/12/12361171QV_12_F.JPG",
    category: "clothing",
    color: "black",
    comment: [],
    years: 2020,
    sale: 30,
    count: 1,
  },
  {
    id: 10,
    name: "Nike T-Shirt",
    price: 100,
    description: "Nike T-Shirt is a buatiful T-Shirt",
    image: "https://i02.appmifile.com/633_bbs_en/31/10/2021/635f8cd609.jpg",
    category: "phone",
    color: "blue",
    comment: [],
    years: 2020,
    sale: 30,
    count: 1,
  },
  {
    id: 11,
    name: "Nike T-Shirt",
    price: 100,
    description: "Nike T-Shirt is a buatiful T-Shirt",
    image:
      "http://sneakers.by/image/cache/data/tovary/9/kupit-originalnye-shorty-nike-aw77-alumni-short-633465-014-v-belarusi-461695017-1000x800.jpeg",
    category: "clothing",
    color: "black",
    comment: [],
    years: 2020,
    sale: 30,
    count: 1,
  },
  {
    id: 12,
    name: "Nike T-Shirt",
    price: 100,
    description: "Nike T-Shirt is a buatiful T-Shirt",
    image:
      "https://cdn3.static1-sima-land.com/items/1522750/0/700-nw.jpg?v=1522102342",
    category: "book",
    color: "blue",
    comment: [],
    years: 2020,
    sale: 30,
    count: 1,
  },
  {
    id: 13,
    name: "Nike T-Shirt",
    price: 100,
    description: "Nike T-Shirt is a buatiful T-Shirt",
    image: "https://n2.sdlcdn.com/imgs/b/y/q/663342210244_1-f0219.jpgы",
    category: "book",
    color: "blue",
    comment: [],
    years: 2020,
    sale: 30,
    count: 1,
  },
  {
    id: 14,
    name: "Nike T-Shirt",
    price: 100,
    description: "Nike T-Shirt is a buatiful T-Shirt",
    image:
      "https://booksrus.pl/upload/iblock/f0c/f0c6b3253e389ba00a8fa304dfb81298.jpg",
    category: "book",
    color: "blue",
    comment: [],
    years: 2020,
    sale: 30,
    count: 1,
  },
  {
    id: 15,
    name: "Nike T-Shirt",
    price: 100,
    description: "Nike T-Shirt is a buatiful T-Shirt",
    image: "https://ncrsport.com/img/storage/large/S88113-2.jpg",
    category: "clothing",
    color: "black",
    comment: [],
    years: 2020,
    sale: 30,
    count: 1,
  },
];

export interface checkboxTS {
  color: string;
  checked: boolean;
}
export const checkbox: checkboxTS[] = [
  { color: "black", checked: false },
  { color: "SaddleBrown", checked: false },
  { color: "MidnightBlue", checked: false },
  { color: "gray", checked: false },
];

// sort
